development: &development
  period_of_contagious_days: 15
  minutes_exposed_to_be_at_risk: 15
  mail_user: <%= ENV.fetch("MAIL_USER") %>
  mail_password: <%= ENV.fetch("MAIL_PASSWORD") %>
  days_to_be_healthy: <%= ENV.fetch("DAYS_TO_BE_HEALTHY") %>
  google_api_key: <%= ENV.fetch("GOOGLE_API_KEY") %>

test: 
  <<: *development

production: &production
  period_of_contagious_days: 15
  minutes_exposed_to_be_at_risk: 15
  mail_user: <%= ENV.fetch("MAIL_USER") %>
  mail_password: <%= ENV.fetch("MAIL_PASSWORD") %>
  days_to_be_healthy: <%= ENV.fetch("DAYS_TO_BE_HEALTHY") %>
  google_api_key: <%= ENV.fetch("GOOGLE_API_KEY") %>