development: &development
  period_of_contagious_days: 15
  minutes_exposed_to_be_at_risk: 15

test: 
  <<: *development

production: &production
  perdiod_of_contagious_days: 15
  minutes_exposed_to_be_at_risk: 15