development: &development
  period_of_contagious_days: 15
  minutes_exposed_to_be_at_risk: 1
  mail_user: <%= ENV.fetch("MAIL_USER") %>
  mail_password: <%= ENV.fetch("MAIL_PASSWORD") %>
  days_to_be_healthy: <%= ENV.fetch("DAYS_TO_BE_HEALTHY") %>
  google_api_key: <%= ENV.fetch("GOOGLE_API_KEY") %>
  ruby_server_id: <%= ENV.fetch("RUBY_SERVER_ID") %>
  react_server_id: <%= ENV.fetch("REACT_SERVER_ID") %>
  asp_server_id: <%= ENV.fetch("ASP_SERVER_ID") %>
  react_server_url: <%= ENV.fetch("REACT_SERVER_URL") %>
  asp_server_url: <%= ENV.fetch("ASP_SERVER_URL") %>

test: 
  <<: *development

production: &production
  period_of_contagious_days: 15
  minutes_exposed_to_be_at_risk: 15
  mail_user: <%= ENV.fetch("MAIL_USER") %>
  mail_password: <%= ENV.fetch("MAIL_PASSWORD") %>
  days_to_be_healthy: <%= ENV.fetch("DAYS_TO_BE_HEALTHY") %>
  google_api_key: <%= ENV.fetch("GOOGLE_API_KEY") %>
  ruby_server_id: <%= ENV.fetch("RUBY_SERVER_ID") %>
  react_server_id: <%= ENV.fetch("REACT_SERVER_ID") %>
  asp_server_id: <%= ENV.fetch("ASP_SERVER_ID") %>
  react_server_url: <%= ENV.fetch("REACT_SERVER_URL") %>
  asp_server_url: <%= ENV.fetch("ASP_SERVER_URL") %>
